version: "3.9"
services:
  sd:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ../sd-data:/data
      - ../sd-output:/output
      - ../sd-input:/input
      - sd-cache:/root/.cache
    runtime: nvidia
volumes:
  sd-cache:
